iter1: сервис gophermart
real-splendid/gophermart-practicum pull request #1
Opened 2024-08-07 03:28 UTC by real-splendid

2024-08-11 22:52 UTC, avhitrov requested changes
Самый лаконичный диплом из всех проверенных мной, браво! Но есть несколько косяков в работе с БД:
- Next() необходимо закруглять проверкой
- Транзакцию на единственную операцию открывать смысла нет
- Если в транзакции есть SELECT, его необходимо отмечать `FOR UPDATE`, иначе он не попадет в транзакцию.

В остальном, работа норм.

2024-08-11 22:52 UTC, avhitrov commented on internal/storage/postgres_storage.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после вызова Next() необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку. Блок
```
	if err := r.Err(); err != nil {
		return nil, err
	}
```
должен находиться здесь, а не выше.

2024-08-11 22:52 UTC, avhitrov commented on internal/storage/postgres_storage.go
> +	}
Аналогично GetUserAuthInfo

2024-08-11 22:52 UTC, avhitrov commented on internal/storage/postgres_storage.go
> +	tx, err := p.dbConn.Begin(opCtx)
Нет смысла открывать транзакцию ради одного запроса. Один запрос и так выполняется транзакционно-безопасно.

2024-08-11 22:52 UTC, avhitrov commented on internal/storage/postgres_storage.go
> +	}
При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку:
```
if err:= rows.Err(); err != nil {
    return nil, err
}
```

2024-08-11 22:52 UTC, avhitrov commented on internal/storage/postgres_storage.go
> +	r, err := tx.Query(opCtx, `SELECT current, withdrawn FROM balance WHERE user_id = $1;`, userID)
```suggestion
	r, err := tx.Query(opCtx, `SELECT current, withdrawn FROM balance WHERE user_id = $1 FOR UPDATE;`, userID)
```
https://t.me/bushigo/36

2024-08-12 19:12 UTC, real-splendid commented on internal/storage/postgres_storage.go
> +	}
исправил

2024-08-12 19:12 UTC, real-splendid commented on internal/storage/postgres_storage.go
> +	}
исправил

2024-08-12 19:12 UTC, real-splendid commented on internal/storage/postgres_storage.go
> +	tx, err := p.dbConn.Begin(opCtx)
убрал транзакцию

2024-08-12 19:13 UTC, real-splendid commented on internal/storage/postgres_storage.go
> +	}
исправил

2024-08-12 19:13 UTC, real-splendid commented on internal/storage/postgres_storage.go
> +	r, err := tx.Query(opCtx, `SELECT current, withdrawn FROM balance WHERE user_id = $1;`, userID)
посмотрел, пост из тг. добавил `FOR UPDATE`

2024-08-15 21:55 UTC, avhitrov approved these changes
Все ок!

2024-08-15 21:57 UTC, merged